version: "3.9"

services:
  qwen3-rerank-fastapi:
    build: .
    image: qwen3-rerank-fastapi:latest
    container_name: qwen3-rerank
    restart: unless-stopped
    environment:
      HF_TOKEN: ${HF_TOKEN}
      NVIDIA_VISIBLE_DEVICES: 0      # выставите карты при желании
      RERANK_API_KEY: ${RERANK_API_KEY} 
    volumes:
      - /opt/huggingface_cache:/root/.cache/huggingface
    ports:
      - "7092:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
